#!/bin/bash
set -euo pipefail

VMS="plexserver monitor chefserver bastion"
BACKUP_PATH=/mnt/store1/backups/vm-images
LIVE_PATH=/var/lib/libvirt/images/
CONVERT=1

cd $BACKUP_PATH

sub_strip_backing_path() {
  for IMG in $(ls -r $BACKUP_PATH); do
    BACKING_FILE=$(qemu-img info $IMG | grep "backing file:" | awk '{print $3}' || true)
    if [ -z $BACKING_FILE ]; then
      echo $IMG no backing file
    fi
    if [[ "$BACKING_FILE" =~ $LIVE_PATH ]]; then
      if [ $CONVERT == 1 ]; then
        echo $IMG bad - converting
        NEW_BACKING_FILE=$(echo $BACKING_FILE | sed -e "s,$LIVE_PATH,,")
        qemu-img rebase -u -b $NEW_BACKING_FILE $IMG
      else
        echo $IMG needs converting
      fi
    else
      echo $IMG good
    fi
  done
}

sub_validate_chain() {
  for IMG in $(ls -r $BACKUP_PATH); do
    qemu-img info --backing-chain $IMG &> /dev/null || (echo $IMG; true)
  done
}

sub_do_backup() {
  for VM in $VMS; do
    /home/hcooper/backup-tools/fi-backup.sh -d -v -q -b $BACKUP_PATH $VM >> /tmp/backup.log;
  done
  sub_strip_backing_path
  sub_validate_chain
}

sub_help() {
  echo validate_chain
  echo do_backup
  echo strip_backing_path
  echo help
  exit
}

if [ -z ${1+x} ]; then
  sub_help
fi

subcommand=$1
case $subcommand in
  "" | "-h" | "--help")
    sub_help
    ;;
  *)
    shift
    sub_${subcommand} $@
    ;;
esac
